name: Invalidate CloudFront Cache

on:
  push:
    branches:
      - main

jobs:
  invalidate_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Invalidate CloudFront Cache
        uses: dawidd6/action-cloudfront-invalidate@v2.0.0
        with:
          cloudfront_distribution_id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          paths: |
            /index.html
            /assets/*
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}